// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9gM8xYtuW-P_6kSgRD9yyKZEWBarcmLY',
    appId: '1:937694903290:web:61dd05d5a16f8a2dd74243',
    messagingSenderId: '937694903290',
    projectId: 'fyp-project-60161',
    authDomain: 'fyp-project-60161.firebaseapp.com',
    storageBucket: 'fyp-project-60161.appspot.com',
    measurementId: 'G-6NJWBL9MTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZarMpcsGewmtiK35nKtqWJlLfpu1XCRk',
    appId: '1:937694903290:android:0ecb8dd94d8b5823d74243',
    messagingSenderId: '937694903290',
    projectId: 'fyp-project-60161',
    storageBucket: 'fyp-project-60161.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc-ayYjVxbfiugmkqb6NJxOcLW3pPjZn8',
    appId: '1:937694903290:ios:432237c5d28b31b6d74243',
    messagingSenderId: '937694903290',
    projectId: 'fyp-project-60161',
    storageBucket: 'fyp-project-60161.appspot.com',
    iosBundleId: 'com.example.fypPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc-ayYjVxbfiugmkqb6NJxOcLW3pPjZn8',
    appId: '1:937694903290:ios:d2ace6b828cb4e2cd74243',
    messagingSenderId: '937694903290',
    projectId: 'fyp-project-60161',
    storageBucket: 'fyp-project-60161.appspot.com',
    iosBundleId: 'com.example.fypPro.RunnerTests',
  );
}
